apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: locust-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: alb
  rules:
  - host: locust.info
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: locust-leader-service
            port: 
              number: 8089
---              
apiVersion: v1
kind: Service
metadata:
  name: locust-test-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: locust-leader
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: locust-loadbalancer
#   namespace: locust-test
#   annotations:
#     # service.beta.kubernetes.io/aws-load-balancer-type: "alb"
#     # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
#     kubernetes.io/ingress.class: "alb"
#     alb.ingress.kubernetes.io/scheme: internet-facing
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /*
#             backend:
#               serviceName: locust-leader-service
#               servicePort: 8089

