
apiVersion: v1
kind: Service
metadata:
  name: locust-test-loadbalancer
  namespace: locust-test
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
  selector:
    app: locust-leader

# apiVersion: v1
# kind: Service
# metadata:
#   name: locust-loadbalancer
#   namespace: locust-test
#   annotations:
#     # service.beta.kubernetes.io/aws-load-balancer-type: "alb"
#     # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
#     kubernetes.io/ingress.class: "alb"
#     alb.ingress.kubernetes.io/scheme: internet-facing
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /*
#             backend:
#               serviceName: locust-leader-service
#               servicePort: 8089








# apiVersion: v1
# kind: Service
# metadata:
#   name: locust-test-loadbalancer
# spec:
#   type: LoadBalancer
#   selector:
#     app: locust-leader
#   ports:
#     - protocol: TCP
#       port: 8089